# -*- coding: utf-8 -*-
"""imdb-data-analysis-ml-rating-predictor_copy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyf8e9WNDDl1S3blwZNJRDNJJIxb2BCN

# **📊 IMDB Insights: EDA & ML Classification**

---

## **📌 About This Notebook**

This notebook performs a complete **Exploratory Data Analysis (EDA)** and **Machine Learning** pipeline on a cleaned IMDB dataset of **10,000 titles** spanning Movies, TV Shows, and Web Series.

### **🗂️ Dataset at a Glance**

| Column | Description |
|---|---|
| `showid` | Unique IMDB identifier (e.g. tt0111161) |
| `title` | Title of the show/movie |
| `type` | Movie / TV Show / Web Series |
| `releaseyear` | Year of release |
| `duration` | Runtime (e.g. "142 min") |
| `genres` | Comma-separated genre tags |
| `cast` | Top billed cast members |
| `imdbrating` | IMDb score (1.0 – 9.5) ← **Target** |
| `numvotes` | Total user votes |
| `popularityrank` | Current popularity rank on IMDb |

### **📋 Notebook Structure**

| # | Section | What It Does |
|---|---|---|
| 1 | **Setup & Loading** | Import libs, load data, sanity checks |
| 2 | **EDA** | Distributions, genre analysis, temporal trends |
| 3 | **Feature Engineering** | Duration parsing, log-transforms, genre flags |
| 4 | **Regression Model** | XGBoost → Predict exact IMDb rating (R² ≈ 0.50) |
| 5 | **Classification Model** | XGBoost → Predict "High-Rated" (≥7.5) with **~83% Accuracy** |
| 6 | **Conclusion** | Key insights and future directions |

### **⌒ℐ Business Requirements**

To derive maximum value from this dataset, the following business objectives have been identified:

*   **Quality Forecasting**: Build a regression model to predict user satisfaction (IMDb Rating) using pre-release features.
*   **High-Value Identification**: Implement a classification system to flag 'Premium Content' (≥ 7.5 rating) for strategic promotion.
*   **Genre Portfolio Management**: Analyze genre performance to optimize content production and licensing mix.
*   **Trend Analysis**: Evaluate temporal shifts in audience preferences across decades to identify evergreen genres vs. fading trends.
*   **Metadata Optimization**: Assess how title length, cast size, and duration impact searchability and user ratings.

### **Business Insights**

1. **High-Value Genre Investment**: Documentary, History, and Animation consistently yield the highest average ratings (all >7.3). For a platform focusing on prestige content, these are lower-risk investments compared to Horror, which has the lowest average rating (~6.1).

2. **The 'Survivorship' Trend**: Average ratings were higher from 1960–1990 compared to recent decades. This suggests a survivorship bias where only high-quality older titles remain popular, whereas modern content has a much wider quality variance.

3. **Engagement as a Quality Proxy**: There is a strong positive correlation between the number of votes and the IMDb rating. Titles that manage to 'go viral' and accumulate more votes are significantly more likely to maintain a high rating.

4. **Format Performance**: TV Shows generally hold a higher median rating than Movies. This suggests that the episodic format may be better for building long-term audience satisfaction and loyalty.

5. **Predictive Accuracy**: Our classification model can predict i

## **1.1 Star Schema Implementation**

We will transform the flat dataset into a Star Schema structure to optimize for analytical queries:
- **Fact Table**: `fact_imdb_performance` (Ratings, Votes, Popularity)
- **Dimension Tables**: `dim_titles`, `dim_genres`, `dim_cast`, and `dim_time`.
"""

# 1. Dim_Time: Extract unique temporal information
dim_time = df[['releaseyear', 'endyear', 'decade']].drop_duplicates().reset_index(drop=True)
dim_time['time_id'] = dim_time.index + 1

# 2. Dim_Titles: Core attributes of the shows/movies
dim_titles = df[['showid', 'title', 'type', 'duration', 'isadult', 'url']].drop_duplicates().reset_index(drop=True)

# 3. Dim_Genres: Normalize the comma-separated genres
genre_map = []
for idx, row in df.iterrows():
    if pd.notna(row['genres']):
        for g in row['genres'].split(','):
            genre_map.append({'showid': row['showid'], 'genre_name': g.strip()})
genre_bridge = pd.DataFrame(genre_map)
unique_genres = pd.DataFrame(genre_bridge['genre_name'].unique(), columns=['genre_name'])
unique_genres['genre_id'] = unique_genres.index + 1
dim_genres = unique_genres

# 4. Dim_Cast: Normalize the comma-separated cast
cast_map = []
for idx, row in df.iterrows():
    if pd.notna(row['cast']):
        for c in row['cast'].split(','):
            cast_map.append({'showid': row['showid'], 'cast_name': c.strip()})
cast_bridge = pd.DataFrame(cast_map)
unique_cast = pd.DataFrame(cast_bridge['cast_name'].unique(), columns=['cast_name'])
unique_cast['cast_id'] = unique_cast.index + 1
dim_cast = unique_cast

# 5. Fact Table: Performance Metrics
# Link back to time_id
fact_table = df.merge(dim_time, on=['releaseyear', 'endyear', 'decade'], how='left')
fact_table = fact_table[['showid', 'time_id', 'imdbrating', 'numvotes', 'popularityrank']]
fact_table.rename(columns={'imdbrating': 'rating', 'numvotes': 'votes', 'popularityrank': 'rank'}, inplace=True)

print("Star Schema Created Successfully:")
print(f"- Fact Table Rows: {len(fact_table)}")
print(f"- Title Dimension: {len(dim_titles)}")
print(f"- Genre Dimension: {len(dim_genres)}")
print(f"- Cast Dimension: {len(dim_cast)}")
display(fact_table.head())

from graphviz import Digraph

# Create a new directed graph
dot = Digraph(comment='IMDB Star Schema ERD', graph_attr={'rankdir':'LR', 'bgcolor':'#0d1117', 'fontcolor':'white'})

# Define node style
dot.attr('node', shape='record', style='filled', fillcolor='#161b22', color='#30363d', fontcolor='#c9d1d9', fontname='Arial')

# Fact Table - Using raw strings (r'') to avoid SyntaxWarnings with \l
dot.node('Fact', r'{<fact> FACT_IMDB_PERFORMANCE | showid (FK) \l time_id (FK) \l rating \l votes \l rank \l}')

# Dimension Tables
dot.node('DimTitles', r'{<titles> DIM_TITLES | showid (PK) \l title \l type \l duration \l isadult \l url \l}')
dot.node('DimGenres', r'{<genres> DIM_GENRES | genre_id (PK) \l genre_name \l}')
dot.node('DimCast', r'{<cast> DIM_CAST | cast_id (PK) \l cast_name \l}')
dot.node('DimTime', r'{<time> DIM_TIME | time_id (PK) \l releaseyear \l endyear \l decade \l}')

# Bridge/Junction Tables
dot.node('GenreBridge', r'{<gb> GENRE_BRIDGE | showid (FK) \l genre_id (FK) \l}')
dot.node('CastBridge', r'{<cb> CAST_BRIDGE | showid (FK) \l cast_id (FK) \l}')

# Relationships
dot.attr('edge', color='#58a6ff')
dot.edge('DimTitles:titles', 'Fact:fact')
dot.edge('DimTime:time', 'Fact:fact')
dot.edge('DimTitles:titles', 'GenreBridge:gb')
dot.edge('DimGenres:genres', 'GenreBridge:gb')
dot.edge('DimTitles:titles', 'CastBridge:cb')
dot.edge('DimCast:cast', 'CastBridge:cb')

display(dot)

"""## **1.  Setup & Data Loading**"""

# ── Core libraries ────────────────────────────────────────────────────────────
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from collections import Counter
warnings.filterwarnings('ignore')

# ── ML libraries ──────────────────────────────────────────────────────────────
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (mean_absolute_error, mean_squared_error, r2_score,
                             accuracy_score, classification_report, confusion_matrix)
from xgboost import XGBRegressor, XGBClassifier

# ── Drive Mounting ───────────────────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

# ── Plot style ────────────────────────────────────────────────────────────────
plt.rcParams.update({
    'figure.facecolor': '#0d1117',
    'axes.facecolor':   '#161b22',
    'axes.edgecolor':   '#30363d',
    'axes.labelcolor':  '#c9d1d9',
    'xtick.color':      '#c9d1d9',
    'ytick.color':      '#c9d1d9',
    'text.color':       '#c9d1d9',
    'grid.color':       '#21262d',
    'grid.linestyle':   '--',
    'grid.alpha':       0.5,
})
PALETTE = ['#58a6ff','#f78166','#3fb950','#d2a8ff','#ffa657','#79c0ff','#ff7b72']

# ── Load data ─────────────────────────────────────────────────────────────────
# Path updated to Google Drive location provided
df = pd.read_csv('/content/drive/MyDrive/Vis02/imdb_data_cleaned.csv')
print(f"✅  Loaded  {df.shape[0]:,} rows × {df.shape[1]} columns")
df.head(5)

# ── Quick data audit ─────────────────────────────────────────────────────────
print("📐 Shape:", df.shape)
print("\n🔢 Data Types:")
print(df.dtypes)
print("\n⚠️  Missing Values:")
print(df.isnull().sum()[df.isnull().sum() > 0])
print("\n📊 Numerical Summary:")
df[['releaseyear','imdbrating','numvotes','popularityrank']].describe().round(2)

"""## **2.  Exploratory Data Analysis**"""

# ── 2.1  Content type breakdown ───────────────────────────────────────────────
type_counts = df['type'].value_counts()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Content Type Distribution', fontsize=15, fontweight='bold', color='#c9d1d9')

bars = axes[0].bar(type_counts.index, type_counts.values,
                   color=PALETTE[:3], edgecolor='#30363d', linewidth=0.8)
for bar, v in zip(bars, type_counts.values):
    axes[0].text(bar.get_x()+bar.get_width()/2, bar.get_height()+25,
                 f'{v:,}', ha='center', va='bottom', fontsize=11, color='#c9d1d9')
axes[0].set_title('Count by Type', color='#c9d1d9')
axes[0].set_xlabel('Type'); axes[0].set_ylabel('Count'); axes[0].grid(axis='y')

axes[1].pie(type_counts.values, labels=type_counts.index, autopct='%1.1f%%',
            colors=PALETTE[:3], textprops={'color':'#c9d1d9'}, startangle=90,
            wedgeprops={'edgecolor':'#0d1117','linewidth':1.5})
axes[1].set_title('Share by Type', color='#c9d1d9')

plt.tight_layout(); plt.show()

# ── 2.2  IMDB Rating deep-dive ────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('IMDB Rating Analysis', fontsize=15, fontweight='bold', color='#c9d1d9')

axes[0].hist(df['imdbrating'], bins=45, color='#58a6ff', edgecolor='#0d1117', lw=0.4)
axes[0].axvline(df['imdbrating'].mean(),  color='#f78166', ls='--', lw=2,
                label=f'Mean   {df["imdbrating"].mean():.2f}')
axes[0].axvline(df['imdbrating'].median(),color='#3fb950', ls='--', lw=2,
                label=f'Median {df["imdbrating"].median():.2f}')
axes[0].set_title('Rating Distribution', color='#c9d1d9')
axes[0].set_xlabel('IMDb Rating'); axes[0].set_ylabel('Count')
axes[0].legend(); axes[0].grid(True)

type_order = df['type'].value_counts().index.tolist()
for i, t in enumerate(type_order):
    data = df[df['type']==t]['imdbrating']
    axes[1].boxplot(data, positions=[i], widths=0.5, patch_artist=True,
                    boxprops=dict(facecolor=PALETTE[i], alpha=0.7),
                    medianprops=dict(color='white', linewidth=2),
                    whiskerprops=dict(color='#c9d1d9'),
                    capprops=dict(color='#c9d1d9'),
                    flierprops=dict(marker='o', markerfacecolor=PALETTE[i],
                                    markersize=3, alpha=0.4))
axes[1].set_xticks(range(len(type_order))); axes[1].set_xticklabels(type_order)
axes[1].set_title('Rating by Content Type', color='#c9d1d9')
axes[1].set_ylabel('IMDb Rating'); axes[1].grid(axis='y')

plt.tight_layout(); plt.show()

# ── 2.3  Genre analysis ───────────────────────────────────────────────────────
all_genres = []
for g in df['genres'].dropna():
    all_genres.extend([x.strip() for x in g.split(',')])
genre_counts = Counter(all_genres)
top_genres   = pd.DataFrame(genre_counts.most_common(15), columns=['Genre','Count'])

genre_ratings = {}
for genre in top_genres['Genre']:
    mask = df['genres'].str.contains(genre, na=False)
    genre_ratings[genre] = df.loc[mask,'imdbrating'].mean()

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Genre Analysis', fontsize=15, fontweight='bold', color='#c9d1d9')

colors_g = plt.cm.Blues(np.linspace(0.35, 0.9, len(top_genres)))
axes[0].barh(top_genres['Genre'][::-1], top_genres['Count'][::-1], color=colors_g)
axes[0].set_title('Top 15 Genres — Title Count', color='#c9d1d9')
axes[0].set_xlabel('Number of Titles'); axes[0].grid(axis='x')

gr_df = pd.DataFrame(list(genre_ratings.items()),
                     columns=['Genre','AvgRating']).sort_values('AvgRating')
colors_r = plt.cm.RdYlGn(np.linspace(0.2, 0.85, len(gr_df)))
axes[1].barh(gr_df['Genre'], gr_df['AvgRating'], color=colors_r)
axes[1].set_title('Avg IMDb Rating by Genre', color='#c9d1d9')
axes[1].set_xlabel('Average Rating'); axes[1].set_xlim(5.5, 8.8)
axes[1].grid(axis='x')
for i,(g,r) in enumerate(zip(gr_df['Genre'], gr_df['AvgRating'])):
    axes[1].text(r+0.03, i, f'{r:.2f}', va='center', fontsize=8.5, color='#c9d1d9')

plt.tight_layout(); plt.show()

# ── 2.4  Temporal trends & vote correlation ───────────────────────────────────
df['decade'] = (df['releaseyear'] // 10) * 10
decade_avg  = df[df['decade']>=1960].groupby('decade')['imdbrating'].mean()

fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle('Temporal Trends & Votes Correlation', fontsize=15,
             fontweight='bold', color='#c9d1d9')

axes[0].plot(decade_avg.index, decade_avg.values,
             color='#58a6ff', marker='o', linewidth=2.5, markersize=7)
axes[0].fill_between(decade_avg.index, decade_avg.values,
                     alpha=0.15, color='#58a6ff')
axes[0].set_title('Avg Rating by Decade', color='#c9d1d9')
axes[0].set_xlabel('Decade'); axes[0].set_ylabel('Avg IMDb Rating')
axes[0].grid(True)

sample = df.sample(2500, random_state=42)
sc = axes[1].scatter(np.log1p(sample['numvotes']), sample['imdbrating'],
                     c=sample['popularityrank'], cmap='plasma',
                     alpha=0.4, s=12, edgecolors='none')
cbar = plt.colorbar(sc, ax=axes[1])
cbar.set_label('Popularity Rank', color='#c9d1d9')
plt.setp(cbar.ax.yaxis.get_ticklabels(), color='#c9d1d9')
axes[1].set_title('log(Votes) vs IMDb Rating', color='#c9d1d9')
axes[1].set_xlabel('log(Number of Votes)'); axes[1].set_ylabel('IMDb Rating')
axes[1].grid(True)

plt.tight_layout(); plt.show()

# ── 2.5  Top 10 highest-rated titles ─────────────────────────────────────────
top10 = df.nlargest(10,'imdbrating')[['title','type','releaseyear','genres','imdbrating','numvotes']]
top10 = top10.reset_index(drop=True)
top10.index += 1
print("🏆  Top 10 Highest-Rated IMDB Titles")
top10.style \
    .background_gradient(subset=['imdbrating'], cmap='YlGn') \
    .format({'numvotes':'{:,}','imdbrating':'{:.1f}'})

"""## **3.  Feature Engineering**"""

# ── Parse duration ───────────────────────────────────────────────────────────
def parse_duration(d):
    try:
        parts = str(d).split()
        if 'h' in parts[0]:
            h = int(parts[0].replace('h',''))
            m = int(parts[1].replace('m','')) if len(parts)>1 else 0
            return h*60+m
        return int(parts[0])
    except:
        return np.nan

df_ml = df.copy()
df_ml['duration_mins'] = df_ml['duration'].apply(parse_duration)
df_ml['duration_mins'] = df_ml['duration_mins'].fillna(df_ml['duration_mins'].median())

# ── Log-transform skewed numerics ─────────────────────────────────────────────
df_ml['log_votes'] = np.log1p(df_ml['numvotes'])
df_ml['log_rank']  = np.log1p(df_ml['popularityrank'])

# ── Interaction: votes-to-rank ratio ──────────────────────────────────────────
df_ml['votes_per_rank'] = df_ml['log_votes'] / (df_ml['log_rank'] + 1)

# ── Encode type ───────────────────────────────────────────────────────────────
le = LabelEncoder()
df_ml['type_enc'] = le.fit_transform(df_ml['type'])

# ── Top-15 genre flags ────────────────────────────────────────────────────────
top_genre_list = [g for g,_ in genre_counts.most_common(15)]
for genre in top_genre_list:
    col = f'g_{genre.lower().replace("-","_").replace(" ","_")}'
    df_ml[col] = df_ml['genres'].str.contains(genre, na=False).astype(int)

# ── Additional meta-features ──────────────────────────────────────────────────
df_ml['num_genres'] = df_ml['genres'].fillna('').apply(
    lambda x: len(x.split(',')) if x else 0)
df_ml['title_len']  = df_ml['title'].str.len()
df_ml['cast_size']  = df_ml['cast'].fillna('').apply(
    lambda x: len(x.split(',')) if x else 0)

genre_cols = [c for c in df_ml.columns if c.startswith('g_')]
FEATURES = (['log_votes','log_rank','votes_per_rank','releaseyear','decade',
             'duration_mins','type_enc','title_len','cast_size','num_genres']
            + genre_cols)

print(f"Total features: {len(FEATURES)}")
print("\nFeature list:")
print(FEATURES)

# ── Correlation heatmap ───────────────────────────────────────────────────────
num_cols = ['imdbrating','log_votes','log_rank','votes_per_rank',
            'releaseyear','duration_mins','cast_size','num_genres','type_enc']
corr = df_ml[num_cols].corr()

fig, ax = plt.subplots(figsize=(11, 8))
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f',
            cmap='coolwarm', center=0, linewidths=0.5,
            linecolor='#0d1117', ax=ax, annot_kws={'size':10})
ax.set_title('Feature Correlation Matrix', fontsize=14, fontweight='bold')
plt.tight_layout(); plt.show()

"""## **4.  Regression Model — Predict IMDB Rating**

> **Task:** Predict the exact IMDB rating (continuous, 1.0 – 9.5)  
> **Algorithm:** XGBoost Regressor

"""

X = df_ml[FEATURES]
y = df_ml['imdbrating']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

print(f"Train: {X_train.shape[0]:,}  |  Test: {X_test.shape[0]:,}  |  Features: {len(FEATURES)}")

# ── Train XGBoost Regressor ───────────────────────────────────────────────────
xgb_reg = XGBRegressor(
    n_estimators      = 600,
    learning_rate     = 0.04,
    max_depth         = 7,
    subsample         = 0.80,
    colsample_bytree  = 0.75,
    min_child_weight  = 2,
    reg_alpha         = 0.05,
    reg_lambda        = 1.0,
    random_state      = 42,
    n_jobs            = -1,
)
xgb_reg.fit(X_train, y_train,
            eval_set=[(X_test, y_test)],
            verbose=False)

y_pred_reg = xgb_reg.predict(X_test)
print("✅  Regressor trained!")

"""## **5.  Model Evaluation**"""

# ── Regression metrics ───────────────────────────────────────────────────────
r2   = r2_score(y_test, y_pred_reg)
mae  = mean_absolute_error(y_test, y_pred_reg)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_reg))

print("=" * 50)
print(f"  📈  R² Score  (test)          : {r2:.4f}")
print(f"  📉  MAE                       : {mae:.4f}")
print(f"  📉  RMSE                      : {rmse:.4f}")
print("=" * 50)

# ── Visual evaluation: Actual vs Predicted, Residuals, Feature Importance ────
fig, axes = plt.subplots(1, 3, figsize=(20, 6))
fig.suptitle('Regression Model — Evaluation Dashboard',
             fontsize=15, fontweight='bold', color='#c9d1d9')

# 1) Actual vs Predicted
axes[0].scatter(y_test, y_pred_reg, alpha=0.3, s=12,
                color='#58a6ff', edgecolors='none')
mn, mx = float(y_test.min()), float(y_test.max())
axes[0].plot([mn,mx],[mn,mx],'r--', lw=2, label='Perfect Fit')
axes[0].set_title(f'Actual vs Predicted\nR² = {r2:.4f}', color='#c9d1d9')
axes[0].set_xlabel('Actual Rating'); axes[0].set_ylabel('Predicted Rating')
axes[0].legend(); axes[0].grid(True)

# 2) Residuals histogram
residuals = y_test.values - y_pred_reg
axes[1].hist(residuals, bins=50, color='#d2a8ff', edgecolor='#0d1117', lw=0.4)
axes[1].axvline(0, color='#f78166', ls='--', lw=2)
axes[1].set_title(f'Residuals Distribution\nMAE={mae:.4f}  RMSE={rmse:.4f}',
                  color='#c9d1d9')
axes[1].set_xlabel('Actual − Predicted'); axes[1].set_ylabel('Count')
axes[1].grid(True)

# 3) Feature importance
fi = pd.Series(xgb_reg.feature_importances_, index=FEATURES).nlargest(15).sort_values()
colors_fi = plt.cm.viridis(np.linspace(0.3, 0.9, len(fi)))
axes[2].barh(fi.index, fi.values, color=colors_fi)
axes[2].set_title('Top 15 Feature Importances', color='#c9d1d9')
axes[2].set_xlabel('Importance Score'); axes[2].grid(axis='x')

plt.tight_layout(); plt.show()

"""## **6. Classification Model — High-Rated Titles (≥ 7.5)**

> **Task:** Binary classification — is the title *high-rated* (IMDB ≥ 7.5) or not?  
> **Algorithm:** XGBoost Classifier  
> **Why this matters:** Streaming platforms, content curators, and investors need to know *"Is this title high-quality?"* — a binary yes/no that's highly actionable.

"""

# ── Build binary target ───────────────────────────────────────────────────────
y_cls = (df_ml['imdbrating'] >= 7.5).astype(int)
print("Class distribution:")
print(y_cls.value_counts().rename({0:'< 7.5  (Not High-Rated)',
                                    1:'≥ 7.5  (High-Rated)'}))

X_tr_c, X_te_c, y_tr_c, y_te_c = train_test_split(
    X, y_cls, test_size=0.2, random_state=42, stratify=y_cls)

xgb_clf = XGBClassifier(
    n_estimators     = 500,
    learning_rate    = 0.05,
    max_depth        = 6,
    subsample        = 0.80,
    colsample_bytree = 0.80,
    min_child_weight = 2,
    reg_alpha        = 0.05,
    random_state     = 42,
    n_jobs           = -1,
    eval_metric      = 'logloss',
    use_label_encoder= False,
)
xgb_clf.fit(X_tr_c, y_tr_c, eval_set=[(X_te_c, y_te_c)], verbose=False)

y_pred_cls = xgb_clf.predict(X_te_c)
acc = accuracy_score(y_te_c, y_pred_cls)
print(f"\n🎯  Classification Accuracy : {acc*100:.2f}%")
print("\n📋  Classification Report:")
print(classification_report(y_te_c, y_pred_cls,
                             target_names=['< 7.5','≥ 7.5']))

# ── Confusion matrix & classifier feature importance ─────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle(f'Classification Model — Accuracy {acc*100:.2f}%',
             fontsize=15, fontweight='bold', color='#c9d1d9')

# Confusion matrix
cm = confusion_matrix(y_te_c, y_pred_cls)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['< 7.5','≥ 7.5'],
            yticklabels=['< 7.5','≥ 7.5'],
            ax=axes[0], linewidths=0.5, linecolor='#0d1117',
            annot_kws={'size':14})
axes[0].set_title('Confusion Matrix', color='#c9d1d9')
axes[0].set_xlabel('Predicted'); axes[0].set_ylabel('Actual')

# Feature importance
fi_clf = pd.Series(xgb_clf.feature_importances_,
                   index=FEATURES).nlargest(15).sort_values()
colors_fi2 = plt.cm.plasma(np.linspace(0.3, 0.85, len(fi_clf)))
axes[1].barh(fi_clf.index, fi_clf.values, color=colors_fi2)
axes[1].set_title('Top 15 Feature Importances (Classifier)',
                  color='#c9d1d9')
axes[1].set_xlabel('Importance Score'); axes[1].grid(axis='x')

plt.tight_layout(); plt.show()

# ── Cross-validation for robustness ──────────────────────────────────────────
cv_acc = cross_val_score(xgb_clf, X, y_cls, cv=5,
                         scoring='accuracy', n_jobs=-1)
cv_f1  = cross_val_score(xgb_clf, X, y_cls, cv=5,
                         scoring='f1', n_jobs=-1)

print("5-Fold Cross-Validation Results (Classifier):")
print(f"  Accuracy  : {cv_acc.mean():.4f} ± {cv_acc.std():.4f}")
print(f"  F1 Score  : {cv_f1.mean():.4f}  ± {cv_f1.std():.4f}")

"""## **6.  Conclusion & Key Insights**

---

### **📊 Dataset Summary**
- **10,000 IMDB titles** — 84.2% Movies, 13.3% TV Shows, 2.5% Web Series.
- Average rating is **6.83** (range 1.0 – 9.5); distribution is slightly left-skewed.
- Very low missing data (< 0.5%) — the dataset is clean and ready for modelling.

### 🔍 EDA Takeaways

| Finding | Detail |
|---|---|
| **Top genre** | Drama is the most frequent, followed by Comedy and Action |
| **Highest-rated genres** | Documentary & History consistently average above 7.5 |
| **Rating trend** | Titles from the 1960s–90s show higher averages (survivorship bias) |
| **Votes ↔ Rating** | Strong positive correlation — popular titles attract more votes and higher scores |
| **Type difference** | TV Shows have a slightly higher median rating than Movies |

### **🤖 Model Performance Summary**

| Model | Metric | Score |
|---|---|---|
| XGBoost Regressor | R² (test) | **~0.50** |
| XGBoost Regressor | MAE | **~0.51** |
| XGBoost Classifier (≥7.5) | Accuracy | **~83%** |
| XGBoost Classifier (≥7.5) | 5-CV Accuracy | **~82–83%** |

### **🔮 Future Improvements**
- **NLP on title/description** — TF-IDF or BERT embeddings for semantic features.
- **Director / cast fame score** — proxy based on their other title ratings.
- **Recency weighting** — recent votes may signal a title's sustained relevance.
- **Multi-class rating buckets** — Low / Medium / High / Excellent for richer classification.
- **Temporal train/test split** — simulate real-world "predict new releases" scenario.

"""